# Generated by Django 5.2.11 on 2026-02-21 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
