# Generated by Django 5.2.11 on 2026-02-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_testattempt_active_testattempt_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='active_question',
            field=models.IntegerField(default=1),
        ),
    ]
