# Generated by Django 5.2.11 on 2026-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_testattempt_active_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='selected',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unattempted'), (2, 'Attempted'), (3, 'Unattempted & Marked'), (4, 'Attempted & Marked')], default=1),
        ),
    ]
