# Generated by Django 5.2.11 on 2026-02-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_remove_questionattempt_selected_questionattempt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.ImageField(upload_to='static/options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.ImageField(upload_to='static/options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.ImageField(upload_to='static/options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.ImageField(upload_to='static/options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ImageField(upload_to='static/questions/'),
        ),
    ]
