# Generated by Django 5.2.11 on 2026-02-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_question_option_1_alter_question_option_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='user',
        ),
    ]
