# Generated by Django 5.2.11 on 2026-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_remove_questionattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unattempted'), (2, 'Attempted'), (3, 'Unattempted & Marked'), (4, 'Attempted & Marked'), (5, 'Unseen')], default=5),
        ),
    ]
