# Generated by Django 5.2.11 on 2026-02-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_questionattempt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='selected',
            field=models.IntegerField(default=0),
        ),
    ]
