# Generated by Django 5.2.11 on 2026-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_questionattempt_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unattempted'), (2, 'Attempted'), (3, 'Unattempted & Marked For Review'), (4, 'Attempted & Marked For Review'), (5, 'Unseen')], default=5),
        ),
    ]
