# Generated by Django 5.2.11 on 2026-02-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_alter_questionattempt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
