# Generated by Django 5.2.11 on 2026-02-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_testattempt_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(),
        ),
    ]
