# Generated by Django 5.2.11 on 2026-02-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_alter_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='difficulty',
        ),
    ]
