# Generated by Django 5.2.11 on 2026-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_remove_test_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
