# Generated by Django 5.2.11 on 2026-02-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_alter_question_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
    ]
