# Generated by Django 5.2.11 on 2026-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_remove_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
